username = "user-name"
password = "password"
submitbutton = "submit-button"
addtocart1 = "add-to-cart-sauce-labs-bike-light"
addtocart2 = "add-to-cart-sauce-labs-backpack"
cartlink = "//a[@class='shopping_cart_link']"
checkout = "checkout"
summaryinfolabel = "//div[@class='summary_info_label']"
summarysubtotallabel = "//div[@class='summary_subtotal_label']"
summarytaxlabel = "//div[@class='summary_tax_label']"
totallabel = "//div[@class='summary_info_label summary_total_label']"
finishicon = "finish"
firstname = "first-name"
lastname = "last-name"
postalcode = "postal-code"
continueicon = "continue"
completeheader = "complete-header"
completetext = "complete-text"
button = "btn"
hamburgericon = "react-burger-menu-btn"
logout = "//a[@id='logout_sidebar_link']"
orderplaced = "Thank you for your order!"
orderdispatched = "Your order has been dispatched, and will arrive just as fast as the pony can get there!"
subtotal = "Item total: $39.98"
taxtotal = "Tax: $3.20"
totalamount = "Total: $43.18"

